apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-to-nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-app-to-nginx
  template:
    metadata:
      labels:
        app: web-app-to-nginx
    spec:
      containers:
      - name: web-app-to-nginx
        image: aesir1/web-app-to-nginx:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-to-nginx
spec:
  type: LoadBalancer
  selector:
    app: web-app-to-nginx
  ports:
  - port: 3333
    targetPort: 3000